// <auto-generated />
using System;
using BrightAkademi.Data.Concrete.EfCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrightAkademi.Data.Migrations
{
    [DbContext(typeof(BrightAkademiContext))]
    [Migration("20231012133307_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6016),
                            Description = "Kategorisi silinenleri buraya atacağız",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6019),
                            Name = "Genel",
                            Url = "genel"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6023),
                            Description = "Full Stack Web Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6023),
                            Name = "Full Stack Web Developer",
                            Url = "full-stack-web-developer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6025),
                            Description = "IOS Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6025),
                            Name = "IOS Developer",
                            Url = "ios-developer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6026),
                            Description = "BackEnd Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6027),
                            Name = "BackEnd Developer",
                            Url = "backend-developer"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6028),
                            Description = "FrontEnd Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6029),
                            Name = "FrontEnd Developer",
                            Url = "frontend-developer"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6030),
                            Description = "Java Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6030),
                            Name = "Java Developer",
                            Url = "java-developer"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FAQ")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Yazılım eğitimi veren ana kucağı",
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6796),
                            Email = "info.wissenakademie.com",
                            FAQ = "Bilgim olmalı mı ? Eğitim durumum ne olmalı ?.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(6797),
                            Name = "Wissen Akademie",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.CourseStudent", b =>
                {
                    b.Property<int?>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseStudents");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 3,
                            StudentId = 5
                        },
                        new
                        {
                            CourseId = 3,
                            StudentId = 6
                        },
                        new
                        {
                            CourseId = 4,
                            StudentId = 7
                        },
                        new
                        {
                            CourseId = 4,
                            StudentId = 8
                        },
                        new
                        {
                            CourseId = 5,
                            StudentId = 9
                        },
                        new
                        {
                            CourseId = 5,
                            StudentId = 10
                        },
                        new
                        {
                            CourseId = 6,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 6,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 7,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 7,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 8,
                            StudentId = 5
                        },
                        new
                        {
                            CourseId = 8,
                            StudentId = 6
                        },
                        new
                        {
                            CourseId = 9,
                            StudentId = 7
                        },
                        new
                        {
                            CourseId = 9,
                            StudentId = 8
                        },
                        new
                        {
                            CourseId = 10,
                            StudentId = 9
                        },
                        new
                        {
                            CourseId = 10,
                            StudentId = 10
                        },
                        new
                        {
                            CourseId = 11,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 11,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 12,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 12,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 13,
                            StudentId = 5
                        },
                        new
                        {
                            CourseId = 13,
                            StudentId = 6
                        },
                        new
                        {
                            CourseId = 14,
                            StudentId = 7
                        },
                        new
                        {
                            CourseId = 14,
                            StudentId = 8
                        },
                        new
                        {
                            CourseId = 15,
                            StudentId = 9
                        },
                        new
                        {
                            CourseId = 15,
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8069),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8071),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8074),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8074),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8076),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8076),
                            Name = "Senior"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5697),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5699),
                            Name = "Super Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5702),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5702),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5703),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5704),
                            Name = "Trainees"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5705),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5706),
                            Name = "Trainee"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4188),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Eyşan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Atay",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4196),
                            UserId = 8
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4200),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Ali",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kırgız",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4200),
                            UserId = 9
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4202),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Teyfik",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Zaim",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4202),
                            UserId = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4206),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Hayratlı",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Eskikabadayı",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4207),
                            UserId = 11
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4208),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Cengiz",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Atay",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4208),
                            UserId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4210),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Bade",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Garson",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4210),
                            UserId = 13
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4212),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Şebnem",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Sertuna",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4212),
                            UserId = 14
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4214),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Temmuz",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kocaoğlu",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4214),
                            UserId = 15
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4215),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Bahar",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Tezcan",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4216),
                            UserId = 16
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4217),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Azad",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Karaeski",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4218),
                            UserId = 17
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(7429),
                            EducationInfo = "Zonguldak Bilgisayar Öğretmenliği",
                            Experience = "30",
                            FirstName = "Ramiz",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Karaeski",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(7430),
                            Profession = "Full Stack Web Developer",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(7436),
                            EducationInfo = "Eskişehir Bilgisayar Mühendisliği",
                            Experience = "10",
                            FirstName = "Kenan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Birkan",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(7437),
                            Profession = "IOS Developer",
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(7440),
                            EducationInfo = "Bahçeşehir Üniversitesi Yazılım Mühendisliği",
                            Experience = "2",
                            FirstName = "Ezel",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Bayraktar",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(7440),
                            Profession = "Backend Developer",
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(7443),
                            EducationInfo = "Arel Üniversitesi Elektronik Haberleşme Mühendisliği",
                            Experience = "2",
                            FirstName = "Serdar",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Tezcan",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(7443),
                            Profession = "Frontend Developer",
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(7445),
                            EducationInfo = "Doğuş Üniversitesi",
                            Experience = "2",
                            FirstName = "Selma",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hünel",
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(7446),
                            Profession = "Java Developer",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4977),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4979),
                            Password = "superadmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4982),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4983),
                            Password = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4984),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4985),
                            Password = "ramizkaraeski",
                            Username = "ramizkaraeski"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4986),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4986),
                            Password = "kenanbirkan",
                            Username = "kenanbirkan"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4988),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4988),
                            Password = "ezelbayraktar",
                            Username = "ezelbayraktar"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4989),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4990),
                            Password = "serdartezcan",
                            Username = "serdartezcan"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4991),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4991),
                            Password = "selmahunel",
                            Username = "selmahunel"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4992),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4993),
                            Password = "eysanatay",
                            Username = "eysanatay"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4994),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4994),
                            Password = "alikizgin",
                            Username = "alikizgin"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4996),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4996),
                            Password = "teyfikzaim",
                            Username = "teyfikzaim"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4997),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4998),
                            Password = "hayratlieskikabadayi",
                            Username = "hayratlieskikabadayi"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4999),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(4999),
                            Password = "cengizatay",
                            Username = "cengizatay"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5000),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5001),
                            Password = "badegarson",
                            Username = "badegarson"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5002),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5002),
                            Password = "sebnemsertuna",
                            Username = "sebnemsertuna"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5003),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5004),
                            Password = "temmuzkocaoglu",
                            Username = "temmuzkocaoglu"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5005),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5005),
                            Password = "bahartezcan",
                            Username = "bahartezcan"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5007),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 425, DateTimeKind.Local).AddTicks(5007),
                            Password = "azadkaraeski",
                            Username = "azadkaraeski"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4311),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4325),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4328),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4329),
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4330),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4330),
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4332),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4332),
                            RoleId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4333),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4334),
                            RoleId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4335),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4335),
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4336),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4337),
                            RoleId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4338),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4338),
                            RoleId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4339),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4340),
                            RoleId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4341),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4341),
                            RoleId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4343),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4343),
                            RoleId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4345),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4345),
                            RoleId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4346),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4347),
                            RoleId = 4,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4348),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4348),
                            RoleId = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4349),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4350),
                            RoleId = 4,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4351),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4351),
                            RoleId = 4,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4352),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(4353),
                            RoleId = 4,
                            UserId = 17
                        });
                });

            modelBuilder.Entity("BrightWeb.Entity.Concrete.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishCourseTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("HowManyMonths")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartCourseTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotalCourseHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 2,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap react react native c# .net javascript node.js ajax",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8900),
                            Description = "Full Stack Developer eğitimi kapsamlı bir eğitim.",
                            Experience = "Bu eğitim sayesinde;Temel ve ileri veritabanı mantığını, Web’in ve yazılımın çalışma prensibini ve tüm süreçlerini, Yeni nesil tüm programlama araç ve dillerini, Back end programlamayı ve API yazmayı, Uçtan uca bir proje geliştirmeyi öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8903),
                            Name = "Full Stack Web Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 1,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 2,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap react react native c# .net javascript node.js ajax",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8924),
                            Description = "Full Stack Developer eğitimi kapsamlı bir eğitim.",
                            Experience = "Bu eğitim sayesinde;Temel ve ileri veritabanı mantığını, Web’in ve yazılımın çalışma prensibini ve tüm süreçlerini, Yeni nesil tüm programlama araç ve dillerini, Back end programlamayı ve API yazmayı, Uçtan uca bir proje geliştirmeyi öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "4",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8924),
                            Name = "Full Stack Web Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 1,
                            TotalCourseHours = "400"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 2,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap react react native c# .net javascript node.js ajax",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8930),
                            Description = "Full Stack Developer eğitimi kapsamlı bir eğitim.",
                            Experience = "Bu eğitim sayesinde;Temel ve ileri veritabanı mantığını, Web’in ve yazılımın çalışma prensibini ve tüm süreçlerini, Yeni nesil tüm programlama araç ve dillerini, Back end programlamayı ve API yazmayı, Uçtan uca bir proje geliştirmeyi öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "6",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8930),
                            Name = "Full Stack Web Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 1,
                            TotalCourseHours = "600"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 3,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Swift",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8934),
                            Description = "IOS Developer",
                            Experience = "Bu eğitimde IOS Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak swift programını öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8935),
                            Name = "IOS Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 2,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 3,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Swift",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8940),
                            Description = "IOS Developer",
                            Experience = "Bu eğitimde IOS Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak swift programını öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8941),
                            Name = "IOS Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 2,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 3,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Swift",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8946),
                            Description = "IOS Developer",
                            Experience = "Bu eğitimde IOS Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak swift programını öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8946),
                            Name = "IOS Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 2,
                            TotalCourseHours = "300"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 4,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "c# .net javascript node.js ajax ",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8950),
                            Description = "Backend Developer",
                            Experience = "Bu eğitimde Backend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8951),
                            Name = "Backend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 3,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 4,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "c# .net javascript node.js ajax ",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8957),
                            Description = "Backend Developer",
                            Experience = "Bu eğitimde Backend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8958),
                            Name = "Backend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 3,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 4,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "c# .net javascript node.js ajax ",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8963),
                            Description = "Backend Developer",
                            Experience = "Bu eğitimde Backend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8964),
                            Name = "Backend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 3,
                            TotalCourseHours = "300"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 5,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap javascript react react native",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8969),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Frontend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8970),
                            Name = "Frontend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 4,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 5,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap javascript react react native",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8976),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Frontend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8976),
                            Name = "Frontend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 4,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 5,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap javascript react react native",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8984),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Frontend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8985),
                            Name = "Frontend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 4,
                            TotalCourseHours = "300"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 6,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Java",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8989),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Java Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8990),
                            Name = "Java Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 5,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 6,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Java",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8997),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Java Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(8997),
                            Name = "Java Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 5,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 6,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Java",
                            CreatedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(9002),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Java Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 12, 16, 33, 7, 423, DateTimeKind.Local).AddTicks(9003),
                            Name = "Java Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 5,
                            TotalCourseHours = "300"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.CourseStudent", b =>
                {
                    b.HasOne("BrightWeb.Entity.Concrete.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAkademi.Entity.Concrete.Student", "Student")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Student", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Teacher", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.UserRole", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAkademi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightWeb.Entity.Concrete.Course", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.Category", "Category")
                        .WithMany("Course")
                        .HasForeignKey("CategoryId");

                    b.HasOne("BrightAkademi.Entity.Concrete.Company", "Company")
                        .WithMany("Courses")
                        .HasForeignKey("CompanyId");

                    b.HasOne("BrightAkademi.Entity.Concrete.Level", "Level")
                        .WithMany("Courses")
                        .HasForeignKey("LevelId");

                    b.HasOne("BrightAkademi.Entity.Concrete.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Category");

                    b.Navigation("Company");

                    b.Navigation("Level");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Category", b =>
                {
                    b.Navigation("Course");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Company", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Level", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Student", b =>
                {
                    b.Navigation("CourseStudents");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Teacher", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BrightWeb.Entity.Concrete.Course", b =>
                {
                    b.Navigation("CourseStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
