// <auto-generated />
using System;
using BrightAkademi.Data.Concrete.EfCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrightAkademi.Data.Migrations
{
    [DbContext(typeof(BrightAkademiContext))]
    [Migration("20231014113424_teacher-course2")]
    partial class teachercourse2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3048),
                            Description = "Kategorisi silinenleri buraya atacağız",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3052),
                            Name = "Genel",
                            Url = "genel"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3056),
                            Description = "Full Stack Web Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3056),
                            Name = "Full Stack Web Developer",
                            Url = "full-stack-web-developer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3058),
                            Description = "IOS Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3058),
                            Name = "IOS Developer",
                            Url = "ios-developer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3059),
                            Description = "BackEnd Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3060),
                            Name = "BackEnd Developer",
                            Url = "backend-developer"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3061),
                            Description = "FrontEnd Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3061),
                            Name = "FrontEnd Developer",
                            Url = "frontend-developer"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3063),
                            Description = "Java Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3063),
                            Name = "Java Developer",
                            Url = "java-developer"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FAQ")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Yazılım eğitimi veren ana kucağı",
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3797),
                            Email = "info.wissenakademie.com",
                            FAQ = "Bilgim olmalı mı ? Eğitim durumum ne olmalı ?.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(3799),
                            Name = "Wissen Akademie",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.CourseStudent", b =>
                {
                    b.Property<int?>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseStudents");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 3,
                            StudentId = 5
                        },
                        new
                        {
                            CourseId = 3,
                            StudentId = 6
                        },
                        new
                        {
                            CourseId = 4,
                            StudentId = 7
                        },
                        new
                        {
                            CourseId = 4,
                            StudentId = 8
                        },
                        new
                        {
                            CourseId = 5,
                            StudentId = 9
                        },
                        new
                        {
                            CourseId = 5,
                            StudentId = 10
                        },
                        new
                        {
                            CourseId = 6,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 6,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 7,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 7,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 8,
                            StudentId = 5
                        },
                        new
                        {
                            CourseId = 8,
                            StudentId = 6
                        },
                        new
                        {
                            CourseId = 9,
                            StudentId = 7
                        },
                        new
                        {
                            CourseId = 9,
                            StudentId = 8
                        },
                        new
                        {
                            CourseId = 10,
                            StudentId = 9
                        },
                        new
                        {
                            CourseId = 10,
                            StudentId = 10
                        },
                        new
                        {
                            CourseId = 11,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 11,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 12,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 12,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 13,
                            StudentId = 5
                        },
                        new
                        {
                            CourseId = 13,
                            StudentId = 6
                        },
                        new
                        {
                            CourseId = 14,
                            StudentId = 7
                        },
                        new
                        {
                            CourseId = 14,
                            StudentId = 8
                        },
                        new
                        {
                            CourseId = 15,
                            StudentId = 9
                        },
                        new
                        {
                            CourseId = 15,
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(5422),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(5425),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(5428),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(5428),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(5429),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(5430),
                            Name = "Senior"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(6187),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(6189),
                            Name = "Super Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(6193),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(6193),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(6195),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(6195),
                            Name = "Trainees"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(6196),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(6197),
                            Name = "Trainee"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3616),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Eyşan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Atay",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3623),
                            UserId = 8
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3627),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Ali",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kırgız",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3628),
                            UserId = 9
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3629),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Teyfik",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Zaim",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3630),
                            UserId = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3631),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Hayratlı",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Eskikabadayı",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3631),
                            UserId = 11
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3633),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Cengiz",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Atay",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3633),
                            UserId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3634),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Bade",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Garson",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3635),
                            UserId = 13
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3636),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Şebnem",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Sertuna",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3636),
                            UserId = 14
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3638),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Temmuz",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kocaoğlu",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3638),
                            UserId = 15
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3639),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Bahar",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Tezcan",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3640),
                            UserId = 16
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3641),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Azad",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Karaeski",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(3642),
                            UserId = 17
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(3670),
                            EducationInfo = "Zonguldak Bilgisayar Öğretmenliği",
                            Experience = "30",
                            FirstName = "Ramiz",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Karaeski",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(3682),
                            Profession = "Full Stack Web Developer",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(3686),
                            EducationInfo = "Eskişehir Bilgisayar Mühendisliği",
                            Experience = "10",
                            FirstName = "Kenan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Birkan",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(3687),
                            Profession = "IOS Developer",
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(3689),
                            EducationInfo = "Bahçeşehir Üniversitesi Yazılım Mühendisliği",
                            Experience = "2",
                            FirstName = "Ezel",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Bayraktar",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(3690),
                            Profession = "Backend Developer",
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(3692),
                            EducationInfo = "Arel Üniversitesi Elektronik Haberleşme Mühendisliği",
                            Experience = "2",
                            FirstName = "Serdar",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Tezcan",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(3692),
                            Profession = "Frontend Developer",
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(3694),
                            EducationInfo = "Doğuş Üniversitesi",
                            Experience = "2",
                            FirstName = "Selma",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hünel",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(3694),
                            Profession = "Java Developer",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.TeacherCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCourses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            TeacherId = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(291),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(296)
                        },
                        new
                        {
                            CourseId = 2,
                            TeacherId = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(297),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(298)
                        },
                        new
                        {
                            CourseId = 3,
                            TeacherId = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(299),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(300)
                        },
                        new
                        {
                            CourseId = 4,
                            TeacherId = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(301),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(301)
                        },
                        new
                        {
                            CourseId = 5,
                            TeacherId = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(302),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(303)
                        },
                        new
                        {
                            CourseId = 6,
                            TeacherId = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(304),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(304)
                        },
                        new
                        {
                            CourseId = 7,
                            TeacherId = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(305),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(306)
                        },
                        new
                        {
                            CourseId = 8,
                            TeacherId = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(307),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(307)
                        },
                        new
                        {
                            CourseId = 9,
                            TeacherId = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(308),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(309)
                        },
                        new
                        {
                            CourseId = 10,
                            TeacherId = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(310),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(310)
                        },
                        new
                        {
                            CourseId = 11,
                            TeacherId = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(311),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(312)
                        },
                        new
                        {
                            CourseId = 12,
                            TeacherId = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(313),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(313)
                        },
                        new
                        {
                            CourseId = 13,
                            TeacherId = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(314),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(315)
                        },
                        new
                        {
                            CourseId = 14,
                            TeacherId = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(316),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(316)
                        },
                        new
                        {
                            CourseId = 15,
                            TeacherId = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(317),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 412, DateTimeKind.Local).AddTicks(318)
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4589),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4592),
                            Password = "superadmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4595),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4596),
                            Password = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4597),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4597),
                            Password = "ramizkaraeski",
                            Username = "ramizkaraeski"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4599),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4599),
                            Password = "kenanbirkan",
                            Username = "kenanbirkan"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4600),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4601),
                            Password = "ezelbayraktar",
                            Username = "ezelbayraktar"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4602),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4602),
                            Password = "serdartezcan",
                            Username = "serdartezcan"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4603),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4604),
                            Password = "selmahunel",
                            Username = "selmahunel"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4605),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4605),
                            Password = "eysanatay",
                            Username = "eysanatay"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4606),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4607),
                            Password = "alikizgin",
                            Username = "alikizgin"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4609),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4609),
                            Password = "teyfikzaim",
                            Username = "teyfikzaim"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4611),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4611),
                            Password = "hayratlieskikabadayi",
                            Username = "hayratlieskikabadayi"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4612),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4613),
                            Password = "cengizatay",
                            Username = "cengizatay"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4614),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4615),
                            Password = "badegarson",
                            Username = "badegarson"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4616),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4616),
                            Password = "sebnemsertuna",
                            Username = "sebnemsertuna"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4618),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4619),
                            Password = "temmuzkocaoglu",
                            Username = "temmuzkocaoglu"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4620),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4621),
                            Password = "bahartezcan",
                            Username = "bahartezcan"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4622),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 411, DateTimeKind.Local).AddTicks(4623),
                            Password = "azadkaraeski",
                            Username = "azadkaraeski"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1345),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1360),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1363),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1363),
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1365),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1365),
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1367),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1367),
                            RoleId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1368),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1369),
                            RoleId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1370),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1370),
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1371),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1372),
                            RoleId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1374),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1374),
                            RoleId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1376),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1376),
                            RoleId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1377),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1378),
                            RoleId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1379),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1379),
                            RoleId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1380),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1380),
                            RoleId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1382),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1382),
                            RoleId = 4,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1383),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1384),
                            RoleId = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1385),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1385),
                            RoleId = 4,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1386),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1387),
                            RoleId = 4,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1388),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 408, DateTimeKind.Local).AddTicks(1388),
                            RoleId = 4,
                            UserId = 17
                        });
                });

            modelBuilder.Entity("BrightWeb.Entity.Concrete.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishCourseTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("HowManyMonths")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartCourseTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotalCourseHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 2,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap react react native c# .net javascript node.js ajax",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6448),
                            Description = "Full Stack Developer eğitimi kapsamlı bir eğitim.",
                            Experience = "Bu eğitim sayesinde;Temel ve ileri veritabanı mantığını, Web’in ve yazılımın çalışma prensibini ve tüm süreçlerini, Yeni nesil tüm programlama araç ve dillerini, Back end programlamayı ve API yazmayı, Uçtan uca bir proje geliştirmeyi öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6451),
                            Name = "Full Stack Web Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 1,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 2,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap react react native c# .net javascript node.js ajax",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6473),
                            Description = "Full Stack Developer eğitimi kapsamlı bir eğitim.",
                            Experience = "Bu eğitim sayesinde;Temel ve ileri veritabanı mantığını, Web’in ve yazılımın çalışma prensibini ve tüm süreçlerini, Yeni nesil tüm programlama araç ve dillerini, Back end programlamayı ve API yazmayı, Uçtan uca bir proje geliştirmeyi öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "4",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6473),
                            Name = "Full Stack Web Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 1,
                            TotalCourseHours = "400"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 2,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap react react native c# .net javascript node.js ajax",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6478),
                            Description = "Full Stack Developer eğitimi kapsamlı bir eğitim.",
                            Experience = "Bu eğitim sayesinde;Temel ve ileri veritabanı mantığını, Web’in ve yazılımın çalışma prensibini ve tüm süreçlerini, Yeni nesil tüm programlama araç ve dillerini, Back end programlamayı ve API yazmayı, Uçtan uca bir proje geliştirmeyi öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "6",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6479),
                            Name = "Full Stack Web Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 1,
                            TotalCourseHours = "600"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 3,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Swift",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6483),
                            Description = "IOS Developer",
                            Experience = "Bu eğitimde IOS Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak swift programını öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6483),
                            Name = "IOS Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 2,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 3,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Swift",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6487),
                            Description = "IOS Developer",
                            Experience = "Bu eğitimde IOS Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak swift programını öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6488),
                            Name = "IOS Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 2,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 3,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Swift",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6492),
                            Description = "IOS Developer",
                            Experience = "Bu eğitimde IOS Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak swift programını öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6493),
                            Name = "IOS Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 2,
                            TotalCourseHours = "300"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 4,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "c# .net javascript node.js ajax ",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6497),
                            Description = "Backend Developer",
                            Experience = "Bu eğitimde Backend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6497),
                            Name = "Backend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 3,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 4,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "c# .net javascript node.js ajax ",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6501),
                            Description = "Backend Developer",
                            Experience = "Bu eğitimde Backend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6501),
                            Name = "Backend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 3,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 4,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "c# .net javascript node.js ajax ",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6505),
                            Description = "Backend Developer",
                            Experience = "Bu eğitimde Backend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6506),
                            Name = "Backend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 3,
                            TotalCourseHours = "300"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 5,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap javascript react react native",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6509),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Frontend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6510),
                            Name = "Frontend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 4,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 5,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap javascript react react native",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6584),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Frontend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6584),
                            Name = "Frontend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 4,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 5,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap javascript react react native",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6590),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Frontend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6591),
                            Name = "Frontend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 4,
                            TotalCourseHours = "300"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 6,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Java",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6594),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Java Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6595),
                            Name = "Java Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 5,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 6,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Java",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6599),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Java Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6600),
                            Name = "Java Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 5,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 6,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Java",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6604),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Java Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 34, 23, 410, DateTimeKind.Local).AddTicks(6604),
                            Name = "Java Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 5,
                            TotalCourseHours = "300"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.CourseStudent", b =>
                {
                    b.HasOne("BrightWeb.Entity.Concrete.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAkademi.Entity.Concrete.Student", "Student")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Student", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Teacher", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.TeacherCourse", b =>
                {
                    b.HasOne("BrightWeb.Entity.Concrete.Course", "Course")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAkademi.Entity.Concrete.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.UserRole", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAkademi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightWeb.Entity.Concrete.Course", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.Category", "Category")
                        .WithMany("Course")
                        .HasForeignKey("CategoryId");

                    b.HasOne("BrightAkademi.Entity.Concrete.Company", "Company")
                        .WithMany("Courses")
                        .HasForeignKey("CompanyId");

                    b.HasOne("BrightAkademi.Entity.Concrete.Level", "Level")
                        .WithMany("Courses")
                        .HasForeignKey("LevelId");

                    b.HasOne("BrightAkademi.Entity.Concrete.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Category");

                    b.Navigation("Company");

                    b.Navigation("Level");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Category", b =>
                {
                    b.Navigation("Course");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Company", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Level", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Student", b =>
                {
                    b.Navigation("CourseStudents");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Teacher", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BrightWeb.Entity.Concrete.Course", b =>
                {
                    b.Navigation("CourseStudents");

                    b.Navigation("TeacherCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
