// <auto-generated />
using System;
using BrightAkademi.Data.Concrete.EfCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrightAkademi.Data.Migrations
{
    [DbContext(typeof(BrightAkademiContext))]
    partial class BrightAkademiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5827),
                            Description = "Kategorisi silinenleri buraya atacağız",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5830),
                            Name = "Genel",
                            Url = "genel"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5834),
                            Description = "Full Stack Web Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5834),
                            Name = "Full Stack Web Developer",
                            Url = "full-stack-web-developer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5836),
                            Description = "IOS Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5836),
                            Name = "IOS Developer",
                            Url = "ios-developer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5837),
                            Description = "BackEnd Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5838),
                            Name = "BackEnd Developer",
                            Url = "backend-developer"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5839),
                            Description = "FrontEnd Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5839),
                            Name = "FrontEnd Developer",
                            Url = "frontend-developer"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5841),
                            Description = "Java Developer",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(5841),
                            Name = "Java Developer",
                            Url = "java-developer"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FAQ")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Yazılım eğitimi veren ana kucağı",
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(6542),
                            Email = "info.wissenakademie.com",
                            FAQ = "Bilgim olmalı mı ? Eğitim durumum ne olmalı ?.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(6545),
                            Name = "Wissen Akademie",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.CourseStudent", b =>
                {
                    b.Property<int?>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseStudents");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 3,
                            StudentId = 5
                        },
                        new
                        {
                            CourseId = 3,
                            StudentId = 6
                        },
                        new
                        {
                            CourseId = 4,
                            StudentId = 7
                        },
                        new
                        {
                            CourseId = 4,
                            StudentId = 8
                        },
                        new
                        {
                            CourseId = 5,
                            StudentId = 9
                        },
                        new
                        {
                            CourseId = 5,
                            StudentId = 10
                        },
                        new
                        {
                            CourseId = 6,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 6,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 7,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 7,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 8,
                            StudentId = 5
                        },
                        new
                        {
                            CourseId = 8,
                            StudentId = 6
                        },
                        new
                        {
                            CourseId = 9,
                            StudentId = 7
                        },
                        new
                        {
                            CourseId = 9,
                            StudentId = 8
                        },
                        new
                        {
                            CourseId = 10,
                            StudentId = 9
                        },
                        new
                        {
                            CourseId = 10,
                            StudentId = 10
                        },
                        new
                        {
                            CourseId = 11,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 11,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 12,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 12,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 13,
                            StudentId = 5
                        },
                        new
                        {
                            CourseId = 13,
                            StudentId = 6
                        },
                        new
                        {
                            CourseId = 14,
                            StudentId = 7
                        },
                        new
                        {
                            CourseId = 14,
                            StudentId = 8
                        },
                        new
                        {
                            CourseId = 15,
                            StudentId = 9
                        },
                        new
                        {
                            CourseId = 15,
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8011),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8014),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8016),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8017),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8018),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8018),
                            Name = "Senior"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(5679),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(5681),
                            Name = "Super Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(5685),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(5685),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(5687),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(5687),
                            Name = "Trainer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(5688),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(5689),
                            Name = "Trainee"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2475),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Eyşan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Atay",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2490),
                            UserId = 8
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2497),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Ali",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kırgız",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2498),
                            UserId = 9
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2499),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Teyfik",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Zaim",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2500),
                            UserId = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2501),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Hayratlı",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Eskikabadayı",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2502),
                            UserId = 11
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2503),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Cengiz",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Atay",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2504),
                            UserId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2505),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Bade",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Garson",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2505),
                            UserId = 13
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2507),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Şebnem",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Sertuna",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2507),
                            UserId = 14
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2508),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Temmuz",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kocaoğlu",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2509),
                            UserId = 15
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2510),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Bahar",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Tezcan",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2510),
                            UserId = 16
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2512),
                            EducationalStatus = "Kayıtlı öğrenci başlayacak.",
                            FirstName = "Azad",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Karaeski",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(2512),
                            UserId = 17
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(7270),
                            EducationInfo = "Zonguldak Bilgisayar Öğretmenliği",
                            Experience = "30",
                            FirstName = "Ramiz",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Karaeski",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(7273),
                            Profession = "Full Stack Web Developer",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(7280),
                            EducationInfo = "Eskişehir Bilgisayar Mühendisliği",
                            Experience = "10",
                            FirstName = "Kenan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Birkan",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(7280),
                            Profession = "IOS Developer",
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(7283),
                            EducationInfo = "Bahçeşehir Üniversitesi Yazılım Mühendisliği",
                            Experience = "2",
                            FirstName = "Ezel",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Bayraktar",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(7283),
                            Profession = "Backend Developer",
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(7285),
                            EducationInfo = "Arel Üniversitesi Elektronik Haberleşme Mühendisliği",
                            Experience = "2",
                            FirstName = "Serdar",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Tezcan",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(7285),
                            Profession = "Frontend Developer",
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            Comment = "10 puan",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(7287),
                            EducationInfo = "Doğuş Üniversitesi",
                            Experience = "2",
                            FirstName = "Selma",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hünel",
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(7288),
                            Profession = "Java Developer",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.TeacherCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCourses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            TeacherId = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9202),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9207)
                        },
                        new
                        {
                            CourseId = 2,
                            TeacherId = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9209),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9210)
                        },
                        new
                        {
                            CourseId = 3,
                            TeacherId = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9211),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9211)
                        },
                        new
                        {
                            CourseId = 4,
                            TeacherId = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9212),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9213)
                        },
                        new
                        {
                            CourseId = 5,
                            TeacherId = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9214),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9214)
                        },
                        new
                        {
                            CourseId = 6,
                            TeacherId = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9215),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9215)
                        },
                        new
                        {
                            CourseId = 7,
                            TeacherId = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9216),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9217)
                        },
                        new
                        {
                            CourseId = 8,
                            TeacherId = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9266),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9266)
                        },
                        new
                        {
                            CourseId = 9,
                            TeacherId = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9268),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9268)
                        },
                        new
                        {
                            CourseId = 10,
                            TeacherId = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9269),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9270)
                        },
                        new
                        {
                            CourseId = 11,
                            TeacherId = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9271),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9271)
                        },
                        new
                        {
                            CourseId = 12,
                            TeacherId = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9272),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9272)
                        },
                        new
                        {
                            CourseId = 13,
                            TeacherId = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9273),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9274)
                        },
                        new
                        {
                            CourseId = 14,
                            TeacherId = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9274),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9275)
                        },
                        new
                        {
                            CourseId = 15,
                            TeacherId = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9276),
                            Id = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(9276)
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4753),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4758),
                            Password = "superadmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4761),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4762),
                            Password = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4763),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4764),
                            Password = "ramizkaraeski",
                            Username = "ramizkaraeski"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4765),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4766),
                            Password = "kenanbirkan",
                            Username = "kenanbirkan"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4767),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4767),
                            Password = "ezelbayraktar",
                            Username = "ezelbayraktar"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4769),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4769),
                            Password = "serdartezcan",
                            Username = "serdartezcan"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4770),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4771),
                            Password = "selmahunel",
                            Username = "selmahunel"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4772),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4773),
                            Password = "eysanatay",
                            Username = "eysanatay"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4774),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4774),
                            Password = "alikizgin",
                            Username = "alikizgin"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4776),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4776),
                            Password = "teyfikzaim",
                            Username = "teyfikzaim"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4777),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4778),
                            Password = "hayratlieskikabadayi",
                            Username = "hayratlieskikabadayi"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4779),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4780),
                            Password = "cengizatay",
                            Username = "cengizatay"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4781),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4781),
                            Password = "badegarson",
                            Username = "badegarson"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4783),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4783),
                            Password = "sebnemsertuna",
                            Username = "sebnemsertuna"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4784),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4785),
                            Password = "temmuzkocaoglu",
                            Username = "temmuzkocaoglu"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4786),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4787),
                            Password = "bahartezcan",
                            Username = "bahartezcan"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4788),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 68, DateTimeKind.Local).AddTicks(4788),
                            Password = "azadkaraeski",
                            Username = "azadkaraeski"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4140),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4151),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4155),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4155),
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4157),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4157),
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4158),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4159),
                            RoleId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4160),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4161),
                            RoleId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4162),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4162),
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4163),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4164),
                            RoleId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4165),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4166),
                            RoleId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4167),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4167),
                            RoleId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4168),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4169),
                            RoleId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4170),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4170),
                            RoleId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4171),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4172),
                            RoleId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4173),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4173),
                            RoleId = 4,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4174),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4175),
                            RoleId = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4176),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4176),
                            RoleId = 4,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4178),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4178),
                            RoleId = 4,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4179),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 65, DateTimeKind.Local).AddTicks(4180),
                            RoleId = 4,
                            UserId = 17
                        });
                });

            modelBuilder.Entity("BrightWeb.Entity.Concrete.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishCourseTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("HowManyMonths")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartCourseTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotalCourseHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 2,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap react react native c# .net javascript node.js ajax",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8666),
                            Description = "Full Stack Developer eğitimi kapsamlı bir eğitim.",
                            Experience = "Bu eğitim sayesinde;Temel ve ileri veritabanı mantığını, Web’in ve yazılımın çalışma prensibini ve tüm süreçlerini, Yeni nesil tüm programlama araç ve dillerini, Back end programlamayı ve API yazmayı, Uçtan uca bir proje geliştirmeyi öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8668),
                            Name = "Full Stack Web Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 1,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 2,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap react react native c# .net javascript node.js ajax",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8684),
                            Description = "Full Stack Developer eğitimi kapsamlı bir eğitim.",
                            Experience = "Bu eğitim sayesinde;Temel ve ileri veritabanı mantığını, Web’in ve yazılımın çalışma prensibini ve tüm süreçlerini, Yeni nesil tüm programlama araç ve dillerini, Back end programlamayı ve API yazmayı, Uçtan uca bir proje geliştirmeyi öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "4",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8685),
                            Name = "Full Stack Web Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 1,
                            TotalCourseHours = "400"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 2,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap react react native c# .net javascript node.js ajax",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8689),
                            Description = "Full Stack Developer eğitimi kapsamlı bir eğitim.",
                            Experience = "Bu eğitim sayesinde;Temel ve ileri veritabanı mantığını, Web’in ve yazılımın çalışma prensibini ve tüm süreçlerini, Yeni nesil tüm programlama araç ve dillerini, Back end programlamayı ve API yazmayı, Uçtan uca bir proje geliştirmeyi öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "6",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8690),
                            Name = "Full Stack Web Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 1,
                            TotalCourseHours = "600"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 3,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Swift",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8694),
                            Description = "IOS Developer",
                            Experience = "Bu eğitimde IOS Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak swift programını öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8694),
                            Name = "IOS Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 2,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 3,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Swift",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8699),
                            Description = "IOS Developer",
                            Experience = "Bu eğitimde IOS Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak swift programını öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8700),
                            Name = "IOS Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 2,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 3,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Swift",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8704),
                            Description = "IOS Developer",
                            Experience = "Bu eğitimde IOS Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak swift programını öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8704),
                            Name = "IOS Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 2,
                            TotalCourseHours = "300"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 4,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "c# .net javascript node.js ajax ",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8756),
                            Description = "Backend Developer",
                            Experience = "Bu eğitimde Backend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8757),
                            Name = "Backend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 3,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 4,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "c# .net javascript node.js ajax ",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8762),
                            Description = "Backend Developer",
                            Experience = "Bu eğitimde Backend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8762),
                            Name = "Backend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 3,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 4,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "c# .net javascript node.js ajax ",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8768),
                            Description = "Backend Developer",
                            Experience = "Bu eğitimde Backend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8768),
                            Name = "Backend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 3,
                            TotalCourseHours = "300"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 5,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap javascript react react native",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8772),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Frontend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8772),
                            Name = "Frontend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 4,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 5,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap javascript react react native",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8776),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Frontend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8777),
                            Name = "Frontend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 4,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 5,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "html css bootstrap javascript react react native",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8781),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Frontend Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8781),
                            Name = "Frontend Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 4,
                            TotalCourseHours = "300"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 6,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Java",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8786),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Java Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "1",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 1,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8787),
                            Name = "Java Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 5,
                            TotalCourseHours = "100"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 6,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Java",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8791),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Java Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "2",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 2,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8791),
                            Name = "Java Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 5,
                            TotalCourseHours = "200"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Kuloğlu Mh., Barbaros Blv. Yıldız İş Hanı No:9, 34353 Beşiktaş/İstanbul",
                            CategoryId = 6,
                            Comment = "Çok iyi bir kurs 10 puan",
                            CompanyId = 1,
                            Content = "Java",
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8795),
                            Description = "Frontend Developer",
                            Experience = "Bu eğitimde Java Developer olmak adına seçeceğiniz eğitim seviyesine göre eğitim alacak gerekli programları öğreneceksiniz.",
                            FinishCourseTime = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyMonths = "3",
                            IsActive = false,
                            IsDeleted = false,
                            LevelId = 3,
                            ModifiedDate = new DateTime(2023, 10, 14, 14, 55, 6, 66, DateTimeKind.Local).AddTicks(8795),
                            Name = "Java Developer",
                            Price = 10000,
                            StartCourseTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Açılacak",
                            TeacherId = 5,
                            TotalCourseHours = "300"
                        });
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.CourseStudent", b =>
                {
                    b.HasOne("BrightWeb.Entity.Concrete.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAkademi.Entity.Concrete.Student", "Student")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Student", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Teacher", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.TeacherCourse", b =>
                {
                    b.HasOne("BrightWeb.Entity.Concrete.Course", "Course")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAkademi.Entity.Concrete.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.UserRole", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightAkademi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightWeb.Entity.Concrete.Course", b =>
                {
                    b.HasOne("BrightAkademi.Entity.Concrete.Category", "Category")
                        .WithMany("Course")
                        .HasForeignKey("CategoryId");

                    b.HasOne("BrightAkademi.Entity.Concrete.Company", "Company")
                        .WithMany("Courses")
                        .HasForeignKey("CompanyId");

                    b.HasOne("BrightAkademi.Entity.Concrete.Level", "Level")
                        .WithMany("Courses")
                        .HasForeignKey("LevelId");

                    b.HasOne("BrightAkademi.Entity.Concrete.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Category");

                    b.Navigation("Company");

                    b.Navigation("Level");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Category", b =>
                {
                    b.Navigation("Course");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Company", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Level", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Student", b =>
                {
                    b.Navigation("CourseStudents");
                });

            modelBuilder.Entity("BrightAkademi.Entity.Concrete.Teacher", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BrightWeb.Entity.Concrete.Course", b =>
                {
                    b.Navigation("CourseStudents");

                    b.Navigation("TeacherCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
